/**
 * Note entity from the backend API
 * - id: Auto-generated by backend (number)
 * - createdAt/updatedAt: ISO 8601 strings from backend
 */
export interface Note {
  id?: number;
  title: string;
  content: string;
  createdAt?: string;
  updatedAt?: string;
}

/**
 * DTO for creating/updating notes (excludes server-generated fields)
 */
export interface NotePayload {
  title: string;
  content: string;
}
